
package com.unsa.pmf.ws.service.cache.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.unsa.pmf.ws.service.cache.ObjectFactory;
import com.unsa.pmf.ws.service.cache.SessionImpl;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CacheService", targetNamespace = "http://cache.service.ws.pmf.unsa.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CacheService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.unsa.pmf.ws.service.cache.SessionImpl
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "startService", targetNamespace = "http://cache.service.ws.pmf.unsa.com/", className = "com.unsa.pmf.ws.service.cache.StartService")
    @ResponseWrapper(localName = "startServiceResponse", targetNamespace = "http://cache.service.ws.pmf.unsa.com/", className = "com.unsa.pmf.ws.service.cache.StartServiceResponse")
    public SessionImpl startService(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isServiceStarted", targetNamespace = "http://cache.service.ws.pmf.unsa.com/", className = "com.unsa.pmf.ws.service.cache.IsServiceStarted")
    @ResponseWrapper(localName = "isServiceStartedResponse", targetNamespace = "http://cache.service.ws.pmf.unsa.com/", className = "com.unsa.pmf.ws.service.cache.IsServiceStartedResponse")
    public boolean isServiceStarted(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
