
package com.unsa.pmf.ws.service.cache.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CacheServiceImplService", targetNamespace = "http://impl.cache.service.ws.pmf.unsa.com/", wsdlLocation = "http://localhost:8080/wservice/CacheServiceImpl?wsdl")
public class CacheServiceImplService
    extends Service
{

    private final static URL CACHESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CACHESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CACHESERVICEIMPLSERVICE_QNAME = new QName("http://impl.cache.service.ws.pmf.unsa.com/", "CacheServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/wservice/CacheServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CACHESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CACHESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CacheServiceImplService() {
        super(__getWsdlLocation(), CACHESERVICEIMPLSERVICE_QNAME);
    }

    public CacheServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CACHESERVICEIMPLSERVICE_QNAME, features);
    }

    public CacheServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CACHESERVICEIMPLSERVICE_QNAME);
    }

    public CacheServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CACHESERVICEIMPLSERVICE_QNAME, features);
    }

    public CacheServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CacheServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CacheService
     */
    @WebEndpoint(name = "CacheServiceImplPort")
    public CacheService getCacheServiceImplPort() {
        return super.getPort(new QName("http://impl.cache.service.ws.pmf.unsa.com/", "CacheServiceImplPort"), CacheService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CacheService
     */
    @WebEndpoint(name = "CacheServiceImplPort")
    public CacheService getCacheServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.cache.service.ws.pmf.unsa.com/", "CacheServiceImplPort"), CacheService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CACHESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CACHESERVICEIMPLSERVICE_EXCEPTION;
        }
        return CACHESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
